version: '3'
services:
  kong-database:
    image: postgres:12-alpine
    container_name: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    depends_on:
      - kong-database
    image: kong
    container_name: kong-migrations
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap -v

  kong:
    depends_on:
      - kong-database
    image: kong
    container_name: kong
    restart: always
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_NGINX_HTTP_RESOLVER=8.8.8.8
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
      - KONG_REAL_IP_RECURSIVE=on
    ports:
      - 80:8000
      - 8001:8001
      - 443:8443 
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://127.0.0.1:8001/status"]
      interval: 5s
      timeout: 2s
      retries: 15

  kong-http-log-server:
    build: .
    image: domecloud/kong-http-log-server
    restart: always
    container_name: kong-http-log-server
    volumes: 
      - ./.env:/app/.env
    ports:
      - 8080:8080

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment: 
      - discovery.type=single-node
    ports: 
      - 9200:9200
 
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports: 
      - 5601:5601
